services:
  nodejs:
    build:
      context: ./Eggtec-backend
      dockerfile: Dockerfile
    image:
      node_image
    # container_name:
    #   node_container
    depends_on:
      - postgres
    volumes:
      - ./Eggtec-backend:/usr/src/app         
    command:
      npx nodemon --legacy-watch server.js
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
      NODE_PORT: 3001
    deploy:
      replicas: 3


  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image:
      postgres_image
    container_name:
      postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
    ports:
      - "5433:5432" # local PC port 충돌
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx_image
    container_name: 
      nginx_container
    ports:
    - "81:80"
    - "443:443"
    depends_on:
    - nodejs
    # volumes:
    # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
