services:
  nodejs:
    build:
      context: ./Eggtec-backend
      dockerfile: Dockerfile
    image:
      node_image
    container_name:
      node_container
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./Eggtec-backend:/usr/src/app         
    command:
      npx nodemon server.js
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
      NODE_PORT: 3001
      # 컨테이너간 내부 포트 사용
  nodejs2:
    image:
      node_image
    container_name:
      node_container2
    ports:
      - "3009:3001"
    depends_on:
      - postgres
    volumes:
      - ./Eggtec-backend:/usr/src/app         
      - /usr/src/app/node_modules
    command:
      npx nodemon server.js
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
      NODE_PORT: 3001
      # 컨테이너간 내부 포트 사용

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image:
      postgres_image
    container_name:
      postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
    ports:
      - "5433:5432" # local PC port 충돌
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx_image
    container_name: 
      nginx_container
    ports:
    - "81:80"
    depends_on:
    - nodejs
    - nodejs2
    # volumes:
    # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


#################################

# services:
#   nodejs:
#     build:
#       context: ./Eggtec-backend
#       dockerfile: Dockerfile
#     container_name:
#       node
#     ports:
#       - "3001:3001"
#     depends_on:
#       - postgres
#     volumes:
#       - ./Eggtec-backend:/usr/src/app         
#       - /usr/src/app/node_modules
#     command:
#       npx nodemon server.js

#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: eggtec
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432  
#       # 컨테이너간 내부 포트 사용
#     networks:
#       - app-net


#   postgres:
#     build:
#       context: ./postgres
#       dockerfile: Dockerfile
#     container_name:
#       postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: eggtec
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432  
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#       - app-net

# volumes:
#   postgres-data:

# networks:
#   app-net:
#     driver: bridge
