services:
  nodejs:
    image:
      node_server-nodejs
    container_name:
      node
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    volumes:
      - ./handaTest:/usr/src/app         
      - /usr/src/app/node_modules
    command:
      npx nodemon server.js
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
      # 컨테이너간 내부 포트 사용



  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name:
      postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eggtec
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
    ports:
      - "5433:5432" # local PC port 충돌
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always


  nginx:
    image: nginx
    container_name: nginx
    ports:
    - "81:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf


# services:
#   nodejs:
#     build:
#       context: ./handaTest
#       dockerfile: Dockerfile
#     container_name:
#       node
#     ports:
#       - "3002:3002"
#     depends_on:
#       - postgres
#     volumes:
#       - ./handaTest:/usr/src/app         
#       - /usr/src/app/node_modules
#     command:
#       npx nodemon server.js

#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: eggtec
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432  
#       # 컨테이너간 내부 포트 사용
#     networks:
#       - app-net


#   postgres:
#     build:
#       context: ./postgres
#       dockerfile: Dockerfile
#     container_name:
#       postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: eggtec
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432  
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#       - app-net

# volumes:
#   postgres-data:

# networks:
#   app-net:
#     driver: bridge
